dataset:
  path: '/home/js/gwhd_2021-2'
  images_dir: 'images/'
  subsets:
    train: 'overfit_train.csv'
    test: 'overfit_test.csv'
    val: 'overfit_val.csv'

model:
  model_name: 'yolov7'
  required_img_width: 640
  required_img_height: 640
  pretrained: True

log_dir: 'runs/train/custom-yolov7'

optimizer:
  name: 'adam'
  weight_decay: 0.0005
  lr: 0.001
  momentum: 0.9
  nesterov: True

trainer_params:
  filter_eval_predictions_fn_params:
    confidence_threshold: 0.15
    nms_threshold: 0.45

  mean_average_precision_callback_params:
    iou_threshold: 0.5

  save_best_model_callback_params:
    watch_metric: 'mAP:0.5-0.75'
    greater_is_better: True

  early_stopping_callback_params:
    patience: 12
    watch_metric: 'mAP:0.5-0.75'
    greater_is_better: True
    early_stopping_threshold: 0.001

  model_ema_callback:
    decay: 0.9999
    greater_is_better: True

training_params:
  num_epochs: 300
  per_device_batch_size: 1
  upsample: True
  cosine_lr_scheduler_params:
    num_warmup_epochs: 5
    num_cooldown_epochs: 5
    k_decay: 1
